/**
 * Free-form candidate tags — the open vocabulary the owner asked for on 2026-08-23
 * (`execution-plan.md` change log: "multiple free-form tags/labels … generated by the AI from
 * source content rather than drawn only from a predefined list"), deferred then and built at
 * schema v2.
 *
 * ## Why this file exists at all, rather than trusting the model's strings
 *
 * These tags are a **library index**, not prose. Their whole value is that two imports six months
 * apart put the same place under the same label, so `Italian`, `italian`, `#italian ` and `ITALIAN`
 * have to be one tag or the feature is decoration. The model will not do that reliably no matter
 * how the prompt is worded — measured, one run of the London caption produced `Market Stall` and
 * `Hotel Restaurant` where the next produced `Market stall` and `Hotel restaurant` — so
 * canonicalisation is code, and the prompt only has to get the *content* right.
 *
 * ## The stored form is `normalise()`'s output. This is the load-bearing decision.
 *
 * `canonicaliseTag` returns a **normalised** string (`italian`, `pan asian`, `hidden gem`), not a
 * pretty one, and that is what a caller stores. Casing and punctuation are a rendering concern and
 * live in `tagDisplayLabel`, which is deliberately a separate function with a name that says so.
 *
 * The reason is that there must be exactly one answer to "are these the same tag?"
 * (`current-state.md` §4). `domain/places/normalise.ts` is that answer everywhere else in this
 * codebase — `poi_index.name_norm`, the resolver, saved-places search — and it folds accents and
 * punctuation: `Pan-Asian` and `pan asian` both key to `pan asian`, `Café` and `cafe` both to
 * `cafe`. The database's own `normalize_tag()` only lowercases and trims, so it would keep
 * `pan-asian` and `pan asian` apart. Storing a display label would therefore let two videos the
 * application considers one tag become two rows in the column the filter chips read — a fragmented
 * tag vocabulary being precisely the failure that makes tags worthless.
 *
 * ## Why `tagKey` is `normalise()` **plus** an NFKC pass
 *
 * The obvious version of this function was `normalise()` alone, and it was wrong in a way that
 * only shows up in Korean. `normalise()` is NFK**D**-based, so it decomposes `한식` into six jamo
 * characters, all of which are `\p{L}` and survive its filter. The database normalises to NFK**C**
 * before it stores, which recomposes them back into two syllables. The application would then hold
 * `한식` as six characters and the column would hold it as two — the same tag, two strings, and any
 * comparison between a freshly computed tag and one read back would fail.
 *
 * Brute-forced rather than reasoned about, over every non-surrogate code point in the whole range
 * (1,112,064 probes): `normalise(x)` is **not** an NFKC fixed point for **11,209** of them — every
 * Hangul syllable and every compatibility form that decomposes into jamo. `normalise(x)` followed
 * by `.normalize('NFKC')` is a fixed point for **all** of them. So the NFKC pass is what actually
 * makes the claim `normalize_tag(canonicaliseTag(x)) === canonicaliseTag(x)` true, and it is
 * appended here rather than folded into `normalise()` itself: changing that function would move
 * `poi_index.name_norm` for the entire POI index and force a `NORM_VERSION` bump and a full
 * reload, to fix a problem that only exists where a tag meets a `text` column.
 *
 * The cost, stated rather than buried: casing information is genuinely lost. `BBQ` is stored as
 * `bbq` and renders as `Bbq`; `pan-Asian` loses its hyphen. That is the price of one identity
 * function, and it is cheaper than a fragmented vocabulary.
 */

import { normalise } from '../places/normalise';

/**
 * At most five labels per candidate, enforced here after de-duplication rather than only in the
 * prompt.
 *
 * Five rather than six for a measured reason, not a taste one: Gemini's `responseSchema` validator
 * rejects this schema outright (HTTP 400) when a *nested* array's `maxItems` exceeds 5 — see
 * `integrations/llm/json-schema.ts`'s `tags` comment for the bisection. Keeping the domain cap and
 * the model-facing cap equal means the model is never asked for a tag that would be thrown away.
 */
export const MAX_TAGS_PER_CANDIDATE = 5;

/** Per-tag length, enforced in Zod as well, and measured on the **raw** model string before
 *  normalisation. Two characters so a stray letter cannot become a tag; 28 so a sentence cannot. */
export const MIN_TAG_LENGTH = 2;
export const MAX_TAG_LENGTH = 28;

/**
 * Words that carry no filtering signal on their own. A tag that is *only* these is dropped: the
 * user already knows every saved row is a place, and `categoryHint` already says `restaurant`.
 * Deliberately short — this is not a topic model, it is a list of words we have actually seen
 * models emit as filler.
 */
/**
 * Characters that are letters to Unicode and blank to a human eye.
 *
 * `normalise()` already removes the obvious invisibles — format characters (U+200B ZERO WIDTH
 * SPACE, U+00AD SOFT HYPHEN, U+2060 WORD JOINER) fall to its punctuation filter, and non-spacing
 * marks including every variation selector (U+FE00-FE0F, U+E0100-E01EF) fall to its `\p{Mn}`
 * strip, which is what stops two visually identical tags being distinct and defeating
 * de-duplication.
 *
 * The Hangul fillers do not. They are category `Lo` — real letters as far as `\p{L}` and
 * `[[:alnum:]]` are concerned — and they render as nothing. A crafted caption could otherwise mint
 * a blank, permanent, unclickable filter chip in someone's library. U+3164 HANGUL FILLER is the
 * well-known one, U+115F and U+1160 are its jamo forms, and U+FFA0 is its halfwidth form.
 *
 * The Khmer inherent vowels U+17B4/U+17B5, which are invisible for the same reason, are **not**
 * listed: they are category `Mn`, so `normalise()`'s existing mark strip already removes them.
 * Verified rather than assumed — listing them anyway would have been dead code, and it also
 * tripped `no-misleading-character-class`, which is a fair complaint about putting combining marks
 * in a character class.
 *
 * Stripped from the raw string *before* normalisation, so they can never reach storage — not
 * merely rejected, because a tag of `italian` + U+3164 should become `italian`, not disappear.
 */
const INVISIBLE_LETTERS = /[\u115F\u1160\u3164\uFFA0]/gu;

const EMPTY_TAG_WORDS = new Set([
  'food', 'foodie', 'place', 'places', 'spot', 'spots', 'restaurant', 'restaurants',
  'good', 'great', 'nice', 'best', 'must', 'try', 'visit', 'cool', 'amazing',
  'the', 'a', 'an', 'and', 'this', 'that',
]);

/*
 * There used to be a rule here that stripped a redundant trailing word so `Italian food` and
 * `Italian` would be one tag. **It was removed after measurement, and the removal is the point.**
 * Run against real model output it turned `Street food` into `Street`, and the same rule gives
 * `Comfort food` -> `Comfort` and `Sea food` -> `Sea`. It bought two cosmetic merges
 * (`Italian food` -> `Italian`, `Nepalese cuisine` -> `Nepalese`) that the prompt already asks the
 * model for, and paid for them by destroying the meaning of any tag whose head word is not a
 * cuisine. There is no way to tell those two cases apart without a cuisine list, and a cuisine list
 * is exactly the closed vocabulary this feature exists to escape.
 */

/**
 * The identity of a tag: the repo's single normaliser, then NFKC so the result is the same string
 * the database will hold (see this file's header for the 11,209 Hangul code points that made the
 * second step necessary).
 *
 * The output is idempotent — `tagKey(tagKey(x)) === tagKey(x)` — which is what makes "store the
 * canonical form" and "store the key" the same instruction. Exported for callers holding a raw
 * string, such as a URL parameter or a user-typed filter, that has not been through
 * `canonicaliseTag`.
 */
export function tagKey(raw: string): string {
  return normalise(raw).normalize('NFKC');
}

/**
 * Cleans one model-emitted tag into the form that gets **stored**, or returns `null` if nothing
 * usable is left.
 *
 * Order matters: bound the raw length, strip the `#`/`@` the model sometimes prefixes, normalise,
 * then reject filler. The output is lowercase, accent-folded and punctuation-free — it is a key,
 * not a label. Use `tagDisplayLabel` to show it to a human.
 */
export function canonicaliseTag(raw: string): string | null {
  const trimmed = raw.trim();
  if (trimmed.length < MIN_TAG_LENGTH || trimmed.length > MAX_TAG_LENGTH) return null;

  const key = tagKey(trimmed.replace(/^[#@]+/, '').replace(INVISIBLE_LETTERS, ''));
  // Empty covers both "nothing but punctuation" and "nothing but invisible letters" — the latter
  // only because `INVISIBLE_LETTERS` ran first, since `normalise()` considers them letters.
  if (key === '') return null;

  // The bound is re-checked on the value that is actually **stored**, not just on the raw string
  // Zod saw: `ﬄ` passes a 28-character raw check and canonicalises to three characters each.
  // `key` is already NFKC (see `tagKey`), so this one comparison is the same string the column's
  // CHECK will measure. Over-long tags are dropped, never truncated — a tag cut mid-word is a
  // wrong tag, not a shorter one.
  if (key.length > MAX_TAG_LENGTH) return null;

  const words = key.split(' ');
  if (words.every((w) => EMPTY_TAG_WORDS.has(w))) return null;

  return key;
}

/**
 * How a stored tag is written for a human: `italian` -> `Italian`, `hidden gem` -> `Hidden Gem`.
 *
 * Deliberately a separate function with a name that says "display", so nobody later collapses it
 * back into `canonicaliseTag` and reintroduces two spellings of one tag into storage. Nothing here
 * is ever compared, matched, de-duplicated or persisted.
 *
 * It is lossy in the way any casing rule is: the input has already been normalised, so `bbq`
 * renders as `Bbq` and `pan asian` as `Pan Asian`. A future exceptions map for acronyms belongs
 * here, in the render path, and nowhere else.
 */
export function tagDisplayLabel(stored: string): string {
  return stored
    .split(' ')
    .map((word) => (word.length === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join(' ');
}

/**
 * Canonicalises a whole tag list: cleans each tag, drops anything that is the candidate's own name
 * (a tag `la nonna` on the place `La Nonna` indexes nothing) or a bare restatement of
 * `categoryHint`, de-duplicates, and caps the result.
 *
 * Pure, and takes the exclusions explicitly rather than reaching for a candidate object, so the
 * rule is testable without building one.
 */
export function canonicaliseTags(
  raw: readonly string[],
  exclusions: { readonly names?: readonly (string | null)[]; readonly categoryHint?: string | null } = {},
): readonly string[] {
  const excluded = new Set<string>();
  for (const name of exclusions.names ?? []) {
    const key = tagKey(name ?? '');
    if (key !== '') excluded.add(key);
  }
  if (exclusions.categoryHint !== undefined && exclusions.categoryHint !== null) {
    const key = tagKey(exclusions.categoryHint);
    if (key !== '') excluded.add(key);
  }

  const seen = new Set<string>();
  const out: string[] = [];
  for (const candidate of raw) {
    const tag = canonicaliseTag(candidate);
    if (tag === null || excluded.has(tag) || seen.has(tag)) continue;
    seen.add(tag);
    out.push(tag);
    if (out.length === MAX_TAGS_PER_CANDIDATE) break;
  }
  return out;
}
