import { describe, expect, it } from 'vitest';

import { NORM_VERSION, normalise, tokenise } from '@/domain/places/normalise';
import benchmark from '../../../docs/evidence/places/benchmark-spec.json';

/**
 * The first half of `10` §4.3's porting test: byte-identical output to the Python `norm()` that
 * produced the 44-case benchmark, for all 44 benchmark queries.
 *
 * Expected values were generated by running the prototype's `norm()` (unmodified, from
 * `docs/evidence/places/resolve-overture-scored.py`) over the same inputs on 2026-08-19 and are
 * pinned here — a golden file, not a re-derivation, because a test that computes the expectation
 * the same way as the code proves nothing.
 *
 * The second half — a 1 000-row sample of *ingested names* — needs an ingest and belongs with
 * tasks 4/5. What cannot be tested until then is recorded rather than quietly skipped.
 */
const PY_NORM: ReadonlyArray<readonly [string, string]> = [
  ['Glitch Coffee & Roasters', 'glitch coffee roasters'],
  ['Onibus Coffee', 'onibus coffee'],
  ['Fuglen Tokyo', 'fuglen tokyo'],
  ['Koffee Mameya', 'koffee mameya'],
  ['Bar Benfiddich', 'bar benfiddich'],
  ['Bar Trench', 'bar trench'],
  ['Afuri', 'afuri'],
  ['Ichiran Shibuya', 'ichiran shibuya'],
  ['猿田彦珈琲', '猿田彦珈琲'],
  ['むぎとオリーブ', 'むきとオリーフ'],
  ['Sarutahiko Coffee', 'sarutahiko coffee'],
  ['Fuglin Tokyo', 'fuglin tokyo'],
  ['Bar Benfidich', 'bar benfidich'],
  ['Port Said', 'port said'],
  ['Cafe Levinsky 41', 'cafe levinsky 41'],
  ['Bellboy', 'bellboy'],
  ['Imperial Craft Cocktail Bar', 'imperial craft cocktail bar'],
  ['Miznon', 'miznon'],
  ['HaKosem', 'hakosem'],
  ['הקוסם', 'הקוסם'],
  ['אורנה ואלה', 'אורנה ואלה'],
  ['Cafe Xoho', 'cafe xoho'],
  ['Anita Gelato', 'anita gelato'],
  ['Port Sayid', 'port sayid'],
  ['Belboy tel aviv', 'belboy tel aviv'],
  ['Oved Daniel Sabich', 'oved daniel sabich'],
  ['Bar 51', 'bar 51'],
  ['Kiln', 'kiln'],
  ['Bar Termini', 'bar termini'],
  ['Monmouth Coffee', 'monmouth coffee'],
  ['Prufrock Coffee', 'prufrock coffee'],
  ['Brat', 'brat'],
  ["Satan's Whiskers", 'satan s whiskers'],
  ['Padella', 'padella'],
  ['Dishoom Shoreditch', 'dishoom shoreditch'],
  ['Bao Soho', 'bao soho'],
  ['Prufrock Cofee', 'prufrock cofee'],
  ['Satans Wiskers', 'satans wiskers'],
  ['The Dove', 'the dove'],
  ['this hidden gem in Shoreditch', 'this hidden gem in shoreditch'],
  ['best coffee ever', 'best coffee ever'],
  ['that little wine bar near the market', 'that little wine bar near the market'],
] as const;

/**
 * The porting traps, each generated from the same Python run. These are the cases that would have
 * passed a Latin-only test and failed on real data (`10` §4).
 */
const PY_NORM_TRAPS: ReadonlyArray<readonly [string, string]> = [
  // `\w` is ASCII-only in JS without the `u` flag: a literal port returns '' for all three.
  ['פלאפל הקוסם', 'פלאפל הקוסם'],
  // Written as escapes on purpose: NFKD decomposes precomposed Hangul into conjoining jamo, which
  // are letters (not combining marks) and therefore survive. The two strings render identically
  // and are different bytes — which is exactly why `poi_index.name_norm`'s CHECK allows 1000
  // characters where `name` allows 300 (migration 0010).
  ['东京 라면', '东京 라면'],
  ['АФУРИ', 'афури'],
  // NFKD decomposes dakuten/handakuten and the mark strip then removes it: が -> か. Lossy, and
  // identical in both implementations, which is what matters.
  ['がんこ寿司', 'かんこ寿司'],
  ['むぎとオリーブ', 'むきとオリーフ'],
  // The kept CJK range is load-bearing: U+30FB KATAKANA MIDDLE DOT is not \p{L} or \p{N}.
  ['中華・そば', '中華・そは'],
  // Fullwidth forms fold under NFKD, which is why the range is `\p{L}`-redundant but harmless.
  ['ＡＦＵＲＩ 阿夫利', 'afuri 阿夫利'],
  ['Ｍｏｎｍｏｕｔｈ', 'monmouth'],
  // Diacritics, an en dash, brackets, apostrophes and emoji all become separators.
  ['BÄR – Bräu (Berlin)', 'bar brau berlin'],
  ['ñoño', 'nono'],
  ['👋 coffee ☕', 'coffee'],
  ['נס-ציונה', 'נס ציונה'],
  // Compatibility decomposition of Ⅳ and ½ (the fraction slash is dropped, so '1 2').
  ['Ⅳ ½ café', 'iv 1 2 cafe'],
  ['ⓐⓑ', 'ab'],
  // Greek breathing marks are non-spacing marks; the capital iota subscript folds away.
  ['ᾈθήνα', 'αθηνα'],
  // Underscore survives, because Python's `\w` includes it.
  ['tel_aviv', 'tel_aviv'],
  ['  Bar   51  ', 'bar 51'],
  ['', ''],
];

describe('normalise', () => {
  it.each([...PY_NORM, ...PY_NORM_TRAPS])(
    'matches the prototype byte-for-byte: %j -> %j',
    (input, want) => {
      expect(normalise(input)).toBe(want);
    },
  );

  it('covers every query in the benchmark spec, so a new case cannot be added untested', () => {
    const pinned = new Set(PY_NORM.map(([input]) => input));
    const queries = benchmark.cases.map((c) => c.query);
    expect(queries.length).toBe(44);
    expect(queries.filter((q) => !pinned.has(q))).toEqual([]);
  });

  it('treats null and undefined as the empty string, as `(s or "")` does', () => {
    expect(normalise(null)).toBe('');
    expect(normalise(undefined)).toBe('');
  });

  it('is idempotent — normalising a normalised name changes nothing', () => {
    // Load-bearing for `ResolveQuery.text` being documented as verbatim: if this ever fails,
    // passing an already-normalised string somewhere becomes an observable bug rather than a
    // wasted call.
    for (const [input] of [...PY_NORM, ...PY_NORM_TRAPS]) {
      expect(normalise(normalise(input))).toBe(normalise(input));
    }
  });

  it('is pinned to a version the loader writes into poi_regions.norm_version', () => {
    // A change to normalise() without a NORM_VERSION bump is the silent-drift failure of `10` §4.
    expect(NORM_VERSION).toBe(1);
    expect(Number.isInteger(NORM_VERSION) && NORM_VERSION > 0).toBe(true);
  });
});

describe('tokenise', () => {
  it('splits the prototype way', () => {
    expect(tokenise('Glitch Coffee & Roasters')).toEqual(['glitch', 'coffee', 'roasters']);
    expect(tokenise('  Bar   51  ')).toEqual(['bar', '51']);
    expect(tokenise('פלאפל הקוסם')).toEqual(['פלאפל', 'הקוסם']);
  });

  it('returns [] rather than [""] for empty input', () => {
    // `''.split(' ')` is `['']`, which would become a one-token query whose coverage is scored
    // against nothing. The prototype's list comprehension drops it; so does this.
    expect(tokenise('')).toEqual([]);
    expect(tokenise('☕')).toEqual([]);
    expect(tokenise(null)).toEqual([]);
  });
});
