/**
 * Every weight, threshold and word list the scorer has, in **one** exported object.
 *
 * That is a requirement, not tidiness. `06` §6.3's closing paragraph: *"These weights and
 * thresholds are calibrated on 44 cases and will be re-fit once the AI Engineer's 50-post golden
 * set (A5) exists, and again if a credentialed provider is benchmarked. They live in one exported
 * constant object with the benchmark as their regression test."* A re-fit must be a diff to this
 * file and nothing else, and it must be obvious from this file alone what the free parameters are.
 *
 * Values started as the prototype's, unchanged: `docs/evidence/places/resolve-overture-scored.py`,
 * which produced `raw-overture-scored.json` and therefore `06` §6.3's 29/12/3 band table. Nothing
 * was re-derived, re-tuned or rounded *in the port*.
 *
 * **Two of them have since been re-fit, both under TLV-RANK-1 (2026-08-27), and both against the
 * first evidence this scorer ever had from a loaded index**: `total` (category 0.18 → 0.10, name
 * 0.72 → 0.80) and `generic` (food-category nouns, and their Hebrew counterparts). Each carries its
 * own argument below; what belongs here is the consequence for the evidence. The 44-case file is a
 * record of a *run at the old values* and is not regenerated by a re-fit, so
 * `tests/unit/places/benchmark-golden.test.ts` now does two separate jobs — it replays the file
 * against the weights the file was measured with, and it re-simulates the 44 cases under whatever
 * `total` currently says, enumerating every case that moves. Do not read a green golden file as
 * "the numbers did not change"; read the enumeration.
 *
 * Two constants that look like parameters are deliberately **not** here:
 *
 *  - Jaro-Winkler's prefix scale, prefix cap and 0.7 boost gate (`jaro-winkler.ts`). They are not
 *    calibration; they are what makes our similarity function equal to the DuckDB one the benchmark
 *    was measured with. Tuning them does not adjust the resolver, it invalidates the evidence.
 *  - `NORM_VERSION` (`normalise.ts`), which is a data-migration fact — it is written into
 *    `poi_regions.norm_version` and a change to it forces a reload.
 *
 * `Object.freeze` is applied because a mutable global weights table is a test-order bug waiting to
 * happen: one test that pokes a threshold to check a band would silently re-band every later test.
 * The type is `readonly` throughout, but `readonly` is compile-time only and the sets are not.
 */

import type { CategoryHint } from '../types';

/** Shape stated explicitly so a re-fit cannot quietly add a knob nothing reads. */
export interface ScoringConstants {
  /**
   * `nameScore = 0.45·whole + 0.55·tokenCoverage − extraTokenPenalty`, then floored at 0
   * (`06` §6.1 step 4). Coverage outweighs whole-string similarity because a caption writes a
   * fragment of the sign — *"Onibus"* for *"Onibus Coffee Nakameguro"* — far more often than it
   * writes the sign.
   */
  readonly name: {
    readonly whole: number;
    readonly tokenCoverage: number;
  };
  /**
   * `score = 0.80·nameScore + 0.10·categoryScore + 0.10·datasetConfidence`. The three sum to 1.00,
   * which is what keeps `score` inside `places.resolution_score`'s `check (… between 0 and 1)`
   * (migration 0005) without a clamp. A re-fit that breaks that sum needs to re-check the CHECK.
   *
   * ## Why category is 0.10 and no longer 0.18 (TLV-RANK-1)
   *
   * `categoryScore` is one bit, and **both sides of it are noisy**. The hint is a model's reading
   * of a caption; the candidate's category is a provider's single-label taxonomy, which files the
   * real `Bar 51` as `restaurant` and a hostel with a bar in it as `bar`. A bit that unreliable
   * may break a tie. It may not overrule the evidence we actually trust.
   *
   * At 0.18 against a name weight of 0.72 it did overrule it. A category agreement was worth
   * `0.18 / 0.72 = 0.25` of name score — **a quarter of the whole name range**, which is the
   * distance from an exact match to a merely similar one. Measured, TLV-14: `Hostel 51` (category
   * `bar`) at 0.822 beat the real `Bar 51` at 0.820 **with a 1.000 name match**, purely on the
   * bonus. Nothing about that is specific to Bar 51; it is what a 0.25 override is for.
   *
   * Halving it to 0.10 puts the ceiling at `0.10 / 0.80 = 0.125`, so the bit still decides ties and
   * near-ties — the job it was added for — and can no longer reverse a name gap. Three properties
   * were checked rather than assumed, on the 15-case live TLV benchmark and on the 44-case golden
   * file (`docs/evidence/places/`):
   *
   *  1. **The freed weight goes to `name`, never to `datasetConfidence`.** Dataset confidence is a
   *     data-quality number about a row, not evidence about *this* query; raising it would let a
   *     well-attested wrong venue outrank a better-named one. And the sum must stay at 1.00 for a
   *     reason beyond the CHECK: with the bands fixed at 0.92/0.80, weights summing to less than
   *     1.00 make the top band arithmetically unreachable for every candidate in the product.
   *  2. **The auto-accept gate is not loosened.** `0.80·1 + 0.10·1 = 0.90 < 0.92`, so a candidate
   *     still cannot reach `preselect` without a category match — exactly as at 0.72/0.18. Nothing
   *     becomes auto-acceptable that was structurally excluded before, and **no case in either
   *     benchmark auto-accepts a venue it did not auto-accept before**.
   *
   *     It costs one, and the cost is real rather than theoretical: TLV-12 (*"Belboy tel aviv"*,
   *     a misspelling) drops from `preselect` at 0.924 to `confirm` at 0.916, four thousandths
   *     under the gate. Its top-1 is Bellboy and it is right both times — the user now taps to
   *     confirm a venue that used to arrive pre-ticked. That is the shape of this trade: a row
   *     whose auto-accept *depended* on the category bonus no longer gets it. Live 7 preselect
   *     before, 6 after; on the 44 recorded cases the count stays 29, with TLV-12 leaving and
   *     LDN-01 entering at margin 0.052, both adjudicated correct. Every one of those is
   *     enumerated in `benchmark-golden.test.ts`, which fails if the set changes again.
   *  3. **0.80 rather than 0.82 or 0.84, and the reason is not the benchmark.** At 0.82 the highest
   *     score obtainable without a category match is `0.82 + 0.10 = 0.92`, the preselect gate
   *     itself, so the band of a perfect name on a maximum-confidence row would be settled by IEEE
   *     rounding. That is not hypothetical — it is TLV-14, which lands on exactly 0.920. At 0.84
   *     and above, `preselect` becomes reachable with no category agreement at all, which is a
   *     loosening of the auto-accept gate that 15 adjudicated cases cannot justify.
   *
   * The 44-case evidence file was recorded at 0.72/0.18/0.10 and is not re-run by this change;
   * `benchmark-golden.test.ts` replays it against those recorded weights and separately simulates
   * the current ones. The band consequences of the re-fit are enumerated there, not summarised.
   */
  readonly total: {
    readonly name: number;
    readonly category: number;
    readonly datasetConfidence: number;
  };
  /**
   * Per surplus distinctive token in the candidate, and its cap. This is what stops *"The
   * Fishmongers Kitchen"* from claiming *"this hidden gem in Shoreditch"* (`06` §6.1 step 4).
   */
  readonly extraTokenPenalty: {
    readonly perToken: number;
    readonly max: number;
  };
  /**
   * Credit for a distinctive query token appearing as a **substring** of the normalised candidate
   * name. Handles agglutinated and prefixed names — `CafeXoho`, `פלאפל הקוסם` — which tokenise
   * apart and would otherwise score on Jaro-Winkler alone. Below 1.0 on purpose: a substring hit is
   * strong evidence, not a token match.
   */
  readonly substringCredit: number;
  /**
   * A token is "distinctive" if it is not in `generic` **and** is longer than this many characters
   * (the prototype's `len(t) > 1`). Counted in code points, not UTF-16 units, so an astral-plane
   * letter counts as one character exactly as it does in Python.
   */
  readonly minDistinctiveTokenLength: number;
  /**
   * `06` §6.2's bands. `preselect` needs `score ≥ preselectScore` **and**
   * `margin ≥ preselectMargin`; `confirm` is `score ≥ confirmScore` with either gate failing;
   * below `confirmScore` is `no_match`.
   *
   * The margin gate is the one doing the important work: a high score with a low margin almost
   * never means "unsure which business", it means "sure of the business, unsure **which branch**",
   * and that is exactly the question a human must settle. Measured at these values: 29 preselect
   * with **zero** false auto-accepts, and all three no-name captions (0.813–0.894) caught by the
   * 0.92 gate (`06` §6.3).
   */
  readonly bands: {
    readonly preselectScore: number;
    readonly preselectMargin: number;
    readonly confirmScore: number;
  };
  /** `ResolveQuery.maxResults === null` → this. `06` §6.1 step 5's top 5. */
  readonly defaultMaxResults: number;
  /**
   * Words that carry no identity in a place name, so they are excluded from token coverage: a query
   * of *"best coffee ever"* has no distinctive token at all, which is how it ends up in `confirm`
   * rather than confidently matching some café.
   *
   * The first block is verbatim from the prototype, including two entries that can never fire and
   * are kept anyway so the list stays diffable against the source of the measured numbers:
   * `'café'` (normalisation strips the accent before this set is consulted, so the reachable
   * spelling is `'cafe'`) and `'a'`, which `minDistinctiveTokenLength` has already removed. City
   * words are in here (`tokyo`, `london`, `tel`, `aviv`) because *"café in Tokyo"* must not match
   * *"Tokyo Coffee"* on the city name.
   *
   * ## The food-category block (TLV-RANK-1)
   *
   * The prototype's list holds `cafe`, `bar` and `restaurant` but stops there, so every *other*
   * word for what a venue sells was scored as identity. Measured consequence, TLV-10: the query
   * *"Anita Gelato"* scored `gelato` as distinctive, `Zucca Cafe & Gelato` matched two of the
   * query's two tokens where a plain `Anita` matched one, and the correct row landed at **rank 4**.
   * That is not a near miss to be tuned away — it is the same defect `cafe` was already in the list
   * to prevent, applied to a word nobody had got to yet.
   *
   * The admission rule, and it is deliberately narrow: **a word belongs here when it names what the
   * venue sells or what kind of venue it is, in the vocabulary a person uses for a place whose name
   * they do not know.** A word that is some venue's *whole* identity does not belong, however
   * generic it looks — `מזנון` is the Hebrew common noun for a canteen and it is also Miznon
   * (TLV-05), so it stays out. Checked, not assumed: against the loaded `tlv` index (10,462 rows)
   * no added word is the entire `name_norm` of more than three rows, and `wine`, `falafel`,
   * `חומוס` and `מזנון` were held back on that test and on the one below.
   *
   * `wine` is the instructive exclusion, and it was **tried and rejected on a measurement, not on
   * a hunch**. It looks exactly like `gelato` and it is already category vocabulary in
   * `categoryTokens.bar`. But NEG-03 is *"that little wine bar near the market"*, a caption that
   * names no venue, and with `wine` generic its only distinctive token is `market`. Run against the
   * live index on 2026-08-27, that turned NEG-03's top-1 from `Tirza wine bar` at 0.793
   * (`no_match`, correctly refused) into **`Beer Market` on Herzl St in Rishon LeZion at 0.815**,
   * back inside `confirm` and shown to the user as a candidate: a negative case pointed 20 km away
   * at a shop that matched on the word `market`. `wine` stays out until something better than one
   * caption says otherwise.
   *
   * The lesson generalises past `wine`. Removing a token from this set's complement also removes it
   * from the prefilter — `queryTokens` builds the `name ILIKE '%token%'` disjunction — so a word
   * admitted here changes *which rows are reachable*, not only how they score.
   *
   * Plurals are listed separately because `tokenise` does no stemming: *"the best bakeries in Tel
   * Aviv"* is a caption our audience actually writes, and `bakeries` is a different token from
   * `bakery`.
   *
   * ## The Hebrew block (TLV-RANK-1)
   *
   * **64% of the loaded index is Hebrew-named** (6,699 of 10,462 rows, measured 2026-08-27), so a
   * list that is generic in English only is generic for a third of our data. Every entry here is
   * the direct translation of an entry that is already in the list — `קפה`/cafe, `בר`/bar,
   * `מסעדה`/restaurant, `בית`/house, `תל`/`אביב` the city words — or of one of the food nouns
   * added above. Nothing was added for which the English side has no counterpart, so this block
   * introduces no new judgement, only symmetry: `גלידה אניטה` is TLV-10 in the other script, and
   * without `גלידה` here it fails the same way.
   *
   * `מאפייה` and `מאפיה` are both listed because the two yod spellings are both current and
   * `normalise()` does not unify them.
   *
   * **What this block measured, stated as measured.** On the 15-case live TLV benchmark it is worth
   * **nothing**, and it costs one place: TLV-07's correct HaKosem branch slips from rank 2 to rank 3
   * because `פיצה הקוסם האיטלקי` now counts two identity words instead of three, pays less
   * extra-token penalty, and climbs 0.029 past it. The case fails either way — its top-1 is the
   * wrong branch with or without this block — and 10/15 is the score with it and without it.
   *
   * It is kept anyway, on two grounds that the benchmark cannot speak to. First, the benchmark is
   * **script-matched to the index by construction** (`handoff-2026-08-27` §6): every Hebrew case in
   * it is a bare venue name, so not one of them contains a Hebrew category noun and none of them
   * *can* show the benefit. Second, the rank slip is the penalty becoming more correct, not less:
   * `פיצה` really is not part of that shop's identity, and a scorer that says so is right even when
   * the row it lifts is one we did not want lifted. What TLV-07 actually needs is branch
   * disambiguation, which no word list provides.
   *
   * That is a judgement on thin evidence and it is written here so it can be reversed on better
   * evidence. Deleting this block is a one-line change and `score.test.ts` says what it protects.
   *
   * **Known and not fixed here:** Hebrew attaches the definite article, so `הבר` and `הפיצה` are
   * single tokens that this set cannot see. Teaching the tokeniser about `ה־` changes
   * `normalise()`'s output, which bumps `NORM_VERSION` and forces a full reload of `poi_index` —
   * a data migration, not a scoring change, and out of this task's scope.
   */
  readonly generic: ReadonlySet<string>;
  /**
   * Per `CategoryHint`, the tokens a candidate's provider category may contain to count as a
   * category match. Indexed **only** by a `CategoryHint` — never by a raw string. `11` §2 ruling 9:
   * the prototype's `CAT_TOKENS[hint]` is a `KeyError` for four of the seven values `09` §4.2's
   * schema can emit, and `categoryHintFor()` (`category-hint.ts`) is the total conversion that
   * makes this table safe to index.
   */
  readonly categoryTokens: Readonly<Record<CategoryHint, ReadonlySet<string>>>;
}

export const SCORING: ScoringConstants = Object.freeze({
  name: Object.freeze({ whole: 0.45, tokenCoverage: 0.55 }),
  total: Object.freeze({ name: 0.8, category: 0.1, datasetConfidence: 0.1 }),
  extraTokenPenalty: Object.freeze({ perToken: 0.04, max: 0.15 }),
  substringCredit: 0.97,
  minDistinctiveTokenLength: 2,
  bands: Object.freeze({ preselectScore: 0.92, preselectMargin: 0.05, confirmScore: 0.8 }),
  defaultMaxResults: 5,
  generic: Object.freeze(
    new Set([
      // The prototype's list, unchanged.
      'cafe', 'café', 'coffee', 'bar', 'restaurant', 'kitchen', 'the', 'and', 'a', 'of', 'de', 'co',
      'company', 'roasters', 'roastery', 'house', 'shop', 'tokyo', 'london', 'tel', 'aviv', 'hidden',
      'gem', 'best', 'ever', 'this', 'that', 'little', 'near', 'in', 'at',
      // Food-category nouns (TLV-RANK-1). What is sold, not who sells it.
      'gelato', 'gelateria', 'pizza', 'pizzeria', 'sushi', 'bakery', 'bakeries', 'brunch',
      'dessert', 'desserts',
      // Hebrew counterparts of entries above (TLV-RANK-1).
      'קפה', 'בר', 'מסעדה', 'בית', 'תל', 'אביב',
      'גלידה', 'גלידריה', 'פיצה', 'סושי', 'מאפייה', 'מאפיה',
    ]),
  ),
  categoryTokens: Object.freeze({
    cafe: Object.freeze(
      new Set(['cafe', 'coffee', 'coffee_shop', 'cafeteria', 'bakery', 'tea', 'dessert',
        'ice_cream', 'juice']),
    ),
    bar: Object.freeze(
      new Set(['bar', 'pub', 'cocktail', 'wine', 'beer', 'brewery', 'nightlife', 'lounge',
        'speakeasy']),
    ),
    restaurant: Object.freeze(
      new Set(['restaurant', 'food', 'dining', 'diner', 'ramen', 'sushi', 'noodle', 'pizza',
        'bistro', 'steak', 'izakaya', 'fast_food', 'buffet', 'deli', 'eatery']),
    ),
  }),
});
