/**
 * Every weight, threshold and word list the scorer has, in **one** exported object.
 *
 * That is a requirement, not tidiness. `06` §6.3's closing paragraph: *"These weights and
 * thresholds are calibrated on 44 cases and will be re-fit once the AI Engineer's 50-post golden
 * set (A5) exists, and again if a credentialed provider is benchmarked. They live in one exported
 * constant object with the benchmark as their regression test."* A re-fit must be a diff to this
 * file and nothing else, and it must be obvious from this file alone what the free parameters are.
 *
 * Values started as the prototype's, unchanged: `docs/evidence/places/resolve-overture-scored.py`,
 * which produced `raw-overture-scored.json` and therefore `06` §6.3's 29/12/3 band table. Nothing
 * was re-derived, re-tuned or rounded *in the port*.
 *
 * **Two of them have since been re-fit against evidence the prototype never had.** `generic` gained
 * the food-category nouns and their Hebrew counterparts (TLV-RANK-1, 2026-08-27). `total` has moved
 * twice: category 0.18 → 0.10 with the freed weight to name (TLV-RANK-1), and then **category and
 * `datasetConfidence` both to 0** (RESOLVE-CONF-1, 2026-08-28), leaving `score = nameScore`
 * corroborated or contradicted by the address. Each carries its own argument below; what belongs
 * here is the consequence for the evidence. The 44-case file is a
 * record of a *run at the old values* and is not regenerated by a re-fit, so
 * `tests/unit/places/benchmark-golden.test.ts` now does two separate jobs — it replays the file
 * against the weights the file was measured with, and it re-simulates the 44 cases under whatever
 * `total` currently says, enumerating every case that moves. Do not read a green golden file as
 * "the numbers did not change"; read the enumeration.
 *
 * Two constants that look like parameters are deliberately **not** here:
 *
 *  - Jaro-Winkler's prefix scale, prefix cap and 0.7 boost gate (`jaro-winkler.ts`). They are not
 *    calibration; they are what makes our similarity function equal to the DuckDB one the benchmark
 *    was measured with. Tuning them does not adjust the resolver, it invalidates the evidence.
 *  - `NORM_VERSION` (`normalise.ts`), which is a data-migration fact — it is written into
 *    `poi_regions.norm_version` and a change to it forces a reload.
 *
 * `Object.freeze` is applied because a mutable global weights table is a test-order bug waiting to
 * happen: one test that pokes a threshold to check a band would silently re-band every later test.
 * The type is `readonly` throughout, but `readonly` is compile-time only and the sets are not.
 */

import type { CategoryHint } from '../types';

/** Shape stated explicitly so a re-fit cannot quietly add a knob nothing reads. */
export interface ScoringConstants {
  /**
   * `nameScore = 0.45·whole + 0.55·tokenCoverage − extraTokenPenalty`, then floored at 0
   * (`06` §6.1 step 4). Coverage outweighs whole-string similarity because a caption writes a
   * fragment of the sign — *"Onibus"* for *"Onibus Coffee Nakameguro"* — far more often than it
   * writes the sign.
   */
  readonly name: {
    readonly whole: number;
    readonly tokenCoverage: number;
  };
  /**
   * `score = 1.00·nameScore`. The three still sum to 1.00 — which is what keeps `score` inside
   * `places.resolution_score`'s `check (… between 0 and 1)` (migration 0005) without a clamp — but
   * two of the three are now **zero**, and that is the change, not an accident of arithmetic.
   *
   * They are kept as named zeros rather than deleted so that this file remains the complete list of
   * free parameters (`06` §6.3), and so that re-admitting either is a diff here plus a
   * re-measurement, exactly as adding one would be.
   *
   * ## Why `datasetConfidence` is 0 (RESOLVE-CONF-1, 2026-08-28)
   *
   * The owner's ruling of 2026-08-28 makes Google Places the resolver the product is built on and
   * Overture legacy infrastructure to phase out. `datasetConfidence` is an Overture column, and on
   * each provider it was failing differently:
   *
   *  - On **Overture** it is a crawler's confidence that a POI exists at all. This file already
   *    argued it is *"a data-quality number about a row, not evidence about this query"* — and then
   *    gave it a tenth of the evidence budget, where a low value vetoes a match every other term
   *    agrees on. Measured: `Kohi Coffee Shop` at confidence 0.295 and `Gelalucci` at 0.34, both
   *    the right venue with an exact address, both held out of `preselect` by that term alone
   *    (`docs/evidence/places/band-policy.md` §1).
   *  - On **Google** there is no such number, so the adapter supplies a constant 0.5. A constant
   *    cannot rank anything; all it does is subtract a flat 0.05 from every score in the system.
   *    Measured on the 16-candidate corpus: removing the term and renormalising the other two moves
   *    the auto-accept count by **zero** (6/16 either way). It was pure dead weight against the gate.
   *
   * ## Why `category` is 0 (RESOLVE-CONF-1)
   *
   * This is the term that was putting the candidate picker in front of the user for venues we had
   * already identified exactly, and it is the direct answer to the owner's ruling in
   * `handoff-2026-08-28-categories-and-the-picker.md` §3.
   *
   * `categoryScore` is one bit produced by comparing a **three-valued** hint (`cafe`, `bar`,
   * `restaurant` — pinned to the extraction schema) against a provider's own taxonomy: ~200 values
   * in Overture's Tel Aviv extract, ~100 primary types in Google. Both sides are noisy and the
   * mismatch is mostly taxonomy, not disagreement about the venue. Measured, on the real corpus:
   * `קפה אירופה` and `Palette Bistro` and `Gelalucci` and `דיזנגוף 99` each match Google's answer
   * on the **whole name, exactly**, and each was held at `confirm` because Google files them under
   * a type our three words do not cover.
   *
   * It was doing the same damage in the other direction on Overture: `band-policy.md` §4 records a
   * category *match* lifting a wrong row over a 1.000 name match (TLV-14).
   *
   * A bit that noisy may not price a decision. It keeps the only job it was ever justified for —
   * breaking a tie — because `rankPlaces`'s comparator still consults `categoryScore` after the
   * total, the name score and the token coverage. What it no longer does is *make* the difference.
   *
   * ## What now protects the auto-accept gate, measured rather than assumed
   *
   * The property this file used to state — *"a candidate cannot reach `preselect` without a
   * category match, because `0.80 + 0.10 < 0.92`"* — is gone with the term, so the replacement has
   * to be named. It is the **margin gate**, and it turns out to be the one that was doing the work
   * all along.
   *
   * `06` §6.3 credits the 0.92 score gate with catching all three no-name captions. Re-measured
   * over the 44 golden cases with the category term as a bonus, NEG-01 scores **0.958** and NEG-02
   * **0.944** — both *over* the score gate. What keeps them out of `preselect` is that their
   * margins are **0.005 and 0.008**: a caption naming no venue matches a hundred rows equally
   * badly, and that is what it looks like. Under the shipped weights they land at 0.858, 0.844 and
   * 0.744, so both gates hold, but the margin is the one that holds structurally.
   *
   * ## The measurement, in full
   *
   * `docs/evidence/places/band-policy.md` §6, replayed over both benchmarks with the real scorer:
   *
   * | | 44 golden (Overture) | 16 real candidates (Google) |
   * |---|---|---|
   * | before | 29 preselect, 0 false | 6 preselect, 0 false |
   * | after  | **31** preselect, 0 false | **11** preselect, 0 false |
   *
   * **Zero false auto-accepts on both, and no case's top-1 changes to a worse venue.** TLV-14 gains
   * an auto-accept and it is `Bar 51`, the venue the case asks for. TLV-10's correct `Anita Sarona`
   * rises out of `no_match` into `confirm`.
   */
  readonly total: {
    readonly name: number;
    /** Zero since RESOLVE-CONF-1. Kept as a named parameter; see above. */
    readonly category: number;
    /** Zero since RESOLVE-CONF-1. Kept as a named parameter; see above. */
    readonly datasetConfidence: number;
  };
  /**
   * Per surplus distinctive token in the candidate, and its cap. This is what stops *"The
   * Fishmongers Kitchen"* from claiming *"this hidden gem in Shoreditch"* (`06` §6.1 step 4).
   */
  readonly extraTokenPenalty: {
    readonly perToken: number;
    readonly max: number;
  };
  /**
   * Credit for a distinctive query token appearing as a **substring** of the normalised candidate
   * name. Handles agglutinated and prefixed names — `CafeXoho`, `פלאפל הקוסם` — which tokenise
   * apart and would otherwise score on Jaro-Winkler alone. Below 1.0 on purpose: a substring hit is
   * strong evidence, not a token match.
   */
  readonly substringCredit: number;
  /**
   * A token is "distinctive" if it is not in `generic` **and** is longer than this many characters
   * (the prototype's `len(t) > 1`). Counted in code points, not UTF-16 units, so an astral-plane
   * letter counts as one character exactly as it does in Python.
   */
  readonly minDistinctiveTokenLength: number;
  /**
   * `06` §6.2's bands. `preselect` needs `score ≥ preselectScore` **and**
   * `margin ≥ preselectMargin`; `confirm` is `score ≥ confirmScore` with either gate failing;
   * below `confirmScore` is `no_match`.
   *
   * The margin gate is the one doing the important work: a high score with a low margin almost
   * never means "unsure which business", it means "sure of the business, unsure **which branch**",
   * and that is exactly the question a human must settle.
   *
   * That was written as an argument and is now a measurement. With the category and confidence
   * terms removed (see `total`), the 44 golden cases give **31 preselect with zero false
   * auto-accepts**, and the three no-name captions land at 0.858 / 0.844 / 0.744 — under the score
   * gate, but with margins of 0.005 / 0.008 / 0.015, which is an order of magnitude under the
   * margin gate. The margin is what a caption that names nothing actually looks like.
   */
  readonly bands: {
    readonly preselectScore: number;
    readonly preselectMargin: number;
    readonly confirmScore: number;
  };
  /**
   * The branch guard (TRACK2-BRANCH, 2026-08-28): when the top-1 and a close rival are plausibly
   * **two branches of one venue**, `preselect` is withheld and the shortlist goes to the user.
   * Full measurement in `docs/evidence/places/branch-guard-2026-08-28.md`.
   *
   * ## Why the margin gate cannot do this job
   *
   * With `total` at name-only, a branch row loses to the bare name by exactly
   * `0.45·(1 − jaroWinkler) + 0.04·(surplus distinctive tokens)` — the whole-string term plus the
   * extra-token penalty. Measured across the six branch families in the 44-case corpus that is
   * **0.031 to 0.097**: `Monmouth Coffee`/`… Company` 0.031, `むぎとオリーブ`/`… 銀座店` 0.069,
   * `Onibus Coffee`/`… Yakumo` 0.072, `Koffee Mameya`/`KOFFEE MAMEYA Kakeru` 0.072,
   * `Bar Termini`/`… Centrale` 0.081, `Padella`/`Padella Shoreditch` 0.095. Every one of those is
   * a measure of **how long the branch suffix is**, not of which branch the caption meant — so the
   * margin gate reads a name-length artefact as confidence and, at 0.05, waves most of them
   * through. TYO-10 is the proof: the bare `むぎとオリーブ` row auto-accepts at margin 0.069 over
   * the Ginza branch the case asks for, 3 km away.
   *
   * ## `rivalScoreBand` — 0.12
   *
   * A rival further than this below the top-1 is not a competing branch, it is a different row
   * that happens to share a name. 0.12 sits in the empty corridor between the highest firing pair
   * (0.0966) and the lowest branch-shaped pair that must **not** fire (TYO-11's 0.1760): 0.023
   * above the first, 0.056 below the second.
   *
   * 0.07 was measured too. It catches TYO-10 alone (30/11/3 rather than 24/17/3) and it is
   * rejected: it sits **0.0025** under TYO-02's identical situation (`Onibus Coffee` vs
   * `Onibus Coffee Yakumo`, 3.1 km apart, caption names no branch). That is a line drawn inside
   * one population, not between two, and it would have to be re-tuned by every change to
   * `extraTokenPenalty` or to Jaro-Winkler.
   *
   * ## Separation is not a knob of this guard
   *
   * How far apart two rows have to be before they are two places is `samePlaceMetres`, below. It
   * is deliberately **not** a branch-guard parameter: the same predicate decides the opposite
   * question on the other side of the picker (collapse two shortlist rows into one place —
   * `docs/ux-when-we-ask.md` §4), and two numbers for one fact is how the two sides end up
   * disagreeing about whether a row exists.
   */
  readonly branchGuard: {
    readonly rivalScoreBand: number;
  };
  /**
   * The radius inside which two rows are **one place**: below it they are one venue recorded
   * twice, above it they are two premises. One number, two consumers with opposite verdicts —
   * `branchRival` (`score.ts`) asks a question above it, and the shortlist collapse
   * (`docs/ux-when-we-ask.md` §4) removes a row below it.
   *
   * **Not fitted here. Inherited**, from the dedup guard inside `resolve_place`, which has treated
   * 75 m as one place since migration 0011: `Kiaans`/`Kiaans Tooting` 18 m apart and
   * `Sycamore Vino Cucina`/`Sycamore Cucina & Bar` 26 m are each one venue recorded twice
   * (`handoff-2026-08-28-categories-and-the-picker.md` §5), and the same investigation records
   * ~500 m as the radius at which distinct venues on one block start merging.
   *
   * The 44-case corpus **cannot discriminate** any value between 75 m and ~500 m: its closest
   * branch pair is 497 m (`Onibus Coffee` and `Onibus Coffee 中目黒三丁目店`) and every pair that
   * actually decides a band is ≥ 1 192 m apart. 250 m was measured as an alternative and produces
   * an identical band table; 75 m is kept because it is the number the rest of the system already
   * uses, and a gap between the two would be a dead zone where a pair is neither collapsed nor
   * asked about. `score.test.ts` pins it, since the benchmark cannot.
   */
  readonly samePlaceMetres: number;
  /**
   * The street-address term (TLV-ADDR-1). Everything about how a caption's `addressHint` is
   * compared to `poi_index.address_line`, and what a match is worth.
   *
   * ## Why the address is not just another similarity
   *
   * `06` §6.1 has no address term and the resolver never saw one, which is the dominant real
   * failure: on 13 real TikTok captions the auto-match rate is 4/16 while the synthetic benchmark
   * says 11/15, and the gap is almost entirely venues whose *name* cannot be matched — a Hebrew
   * caption against a Latin-named row. The address bridges that, because **83% of `address_line`
   * values in the loaded index are Hebrew even where the name is not**: `Kohi Coffee Shop` sits at
   * `בן יהודה 155`, `Brasserie 18` at `לבונטין 19`, `Rustico` at `בזל 42`.
   *
   * ## Measured: Jaro-Winkler on the whole address string is worse than useless
   *
   * Run over 9 true pairs and 10 false pairs from the real corpus and the real index, whole-string
   * Jaro-Winkler scores **0.351 for a true match and 0.964 for a false one** — `אבן גבירול 26` vs
   * `אבן גבירול 70` is a different building on the same street and scores higher than every true
   * cross-script pair. There is no threshold. The ordering is inverted, so the similarity function
   * that works for names is not merely weaker here, it is *backwards*.
   *
   * What separates the same data perfectly is a **house-number gate**: parse both sides into a
   * house number and street tokens, and treat a different number as conclusive evidence of a
   * different place. All 10 false pairs go to exactly 0 on the number alone.
   *
   * ## `streetMatch`, and why the street is a gate rather than a gradient
   *
   * A street name is or is not the same street; "60% the same street" is noise, not evidence.
   * Measured on the same pairs, spelling variants of one street (`איינשטיין` vs `אינשטיין`) score
   * **0.953**, while distinct streets sharing a house number top out at **0.800**
   * (`שלמה המלך 1` vs `המלך ג'ורג' 1` — two real Tel Aviv streets). `streetMatch` sits at 0.90,
   * between those two measurements with room on both sides, and anything below it scores 0.
   *
   * ## `streetOnly`, and the missing house number
   *
   * 9% of the index's addresses carry no digits at all. A street agreeing with no number to
   * confirm it is real but weak evidence — one street holds hundreds of venues — so it is halved
   * rather than either trusted or discarded.
   */
  readonly address: {
    /**
     * The share of the total score the address takes **when, and only when, a comparison was
     * actually possible** — see `addressScore`'s three-valued return in `score.ts`. The base
     * weights are scaled by `1 - weight` for that row, so the three still sum to 1.00 and a
     * perfect everything is still exactly 1.00.
     */
    readonly weight: number;
    /** Below this, street similarity is 0. Not a soft floor: distinct streets score 0. */
    readonly streetMatch: number;
    /** Multiplier when one side has no house number to confirm the street with. */
    readonly streetOnly: number;
    /**
     * Street tokens shorter than this are not required to match. Hebrew street names are full of
     * two-letter particles (`בן`, `אל`) whose Jaro-Winkler similarity to each other is high enough
     * to carry a wrong street over the gate.
     */
    readonly minStreetTokenLength: number;
  };
  /**
   * Words dropped from an address before comparison: street-type nouns and the city and country
   * words a caption appends but `address_line` does not carry.
   *
   * **Deliberately not `generic`.** That set is for *place names* and it contains `בית` — which is
   * the first word of the real street `בית אשל 15`. Reusing it here would delete half of a street
   * name. Two vocabularies that look similar and must not be shared.
   */
  readonly addressNoise: ReadonlySet<string>;
  /**
   * The two pieces of evidence allowed to override a band gate (RECOG-METRICS-2, 2026-08-28), and
   * the single free parameter between them. Both are measured in
   * `docs/evidence/places/recognition-decisive-evidence-2026-08-28.md`; `confidenceOf` in
   * `score.ts` carries the argument for each.
   *
   * Neither adds a *score*. They change which gate a row has to clear, and only ever in the
   * direction of asking the user one fewer question that our own evidence had already answered —
   * which is the owner's ruling of 2026-08-28: *"only ask the user to choose when ambiguity is
   * genuinely unavoidable."*
   */
  readonly decisive: {
    /**
     * F3: how far below the top-1 a rival's **name** score has to sit before the margin gate is
     * waived for an otherwise-exact name.
     *
     * 0.02, and it is a floor rather than a fitted value. The case it exists for is
     * `Palette Bistro` (1.000) against `Paulette` (0.967) — a gap of 0.033. The cases it must
     * **not** admit are two rows under the *same* name, where the gap is exactly 0.000: `The Dove`
     * twice (LDN-13), `Afuri`/`AFURI` (TYO-07), `猿田彦珈琲` twice (TYO-09). There is nothing
     * between 0.000 and 0.033 in either corpus, so any value in that interval behaves identically
     * and 0.02 is the midpoint. It is a **separation** test, not a similarity threshold: raising it
     * only makes the rule fire less often.
     */
    readonly rivalNameSeparation: number;
  };
  /** `ResolveQuery.maxResults === null` → this. `06` §6.1 step 5's top 5. */
  readonly defaultMaxResults: number;
  /**
   * Words that carry no identity in a place name, so they are excluded from token coverage: a query
   * of *"best coffee ever"* has no distinctive token at all, which is how it ends up in `confirm`
   * rather than confidently matching some café.
   *
   * The first block is verbatim from the prototype, including two entries that can never fire and
   * are kept anyway so the list stays diffable against the source of the measured numbers:
   * `'café'` (normalisation strips the accent before this set is consulted, so the reachable
   * spelling is `'cafe'`) and `'a'`, which `minDistinctiveTokenLength` has already removed. City
   * words are in here (`tokyo`, `london`, `tel`, `aviv`) because *"café in Tokyo"* must not match
   * *"Tokyo Coffee"* on the city name.
   *
   * ## The food-category block (TLV-RANK-1)
   *
   * The prototype's list holds `cafe`, `bar` and `restaurant` but stops there, so every *other*
   * word for what a venue sells was scored as identity. Measured consequence, TLV-10: the query
   * *"Anita Gelato"* scored `gelato` as distinctive, `Zucca Cafe & Gelato` matched two of the
   * query's two tokens where a plain `Anita` matched one, and the correct row landed at **rank 4**.
   * That is not a near miss to be tuned away — it is the same defect `cafe` was already in the list
   * to prevent, applied to a word nobody had got to yet.
   *
   * The admission rule, and it is deliberately narrow: **a word belongs here when it names what the
   * venue sells or what kind of venue it is, in the vocabulary a person uses for a place whose name
   * they do not know.** A word that is some venue's *whole* identity does not belong, however
   * generic it looks — `מזנון` is the Hebrew common noun for a canteen and it is also Miznon
   * (TLV-05), so it stays out. Checked, not assumed: against the loaded `tlv` index (10,462 rows)
   * no added word is the entire `name_norm` of more than three rows, and `wine`, `falafel`,
   * `חומוס` and `מזנון` were held back on that test and on the one below.
   *
   * `wine` is the instructive exclusion, and it was **tried and rejected on a measurement, not on
   * a hunch**. It looks exactly like `gelato` and it is already category vocabulary in
   * `categoryTokens.bar`. But NEG-03 is *"that little wine bar near the market"*, a caption that
   * names no venue, and with `wine` generic its only distinctive token is `market`. Run against the
   * live index on 2026-08-27, that turned NEG-03's top-1 from `Tirza wine bar` at 0.793
   * (`no_match`, correctly refused) into **`Beer Market` on Herzl St in Rishon LeZion at 0.815**,
   * back inside `confirm` and shown to the user as a candidate: a negative case pointed 20 km away
   * at a shop that matched on the word `market`. `wine` stays out until something better than one
   * caption says otherwise.
   *
   * The lesson generalises past `wine`. Removing a token from this set's complement also removes it
   * from the prefilter — `queryTokens` builds the `name ILIKE '%token%'` disjunction — so a word
   * admitted here changes *which rows are reachable*, not only how they score.
   *
   * Plurals are listed separately because `tokenise` does no stemming: *"the best bakeries in Tel
   * Aviv"* is a caption our audience actually writes, and `bakeries` is a different token from
   * `bakery`.
   *
   * ## The Hebrew block (TLV-RANK-1)
   *
   * **64% of the loaded index is Hebrew-named** (6,699 of 10,462 rows, measured 2026-08-27), so a
   * list that is generic in English only is generic for a third of our data. Every entry here is
   * the direct translation of an entry that is already in the list — `קפה`/cafe, `בר`/bar,
   * `מסעדה`/restaurant, `בית`/house, `תל`/`אביב` the city words — or of one of the food nouns
   * added above. Nothing was added for which the English side has no counterpart, so this block
   * introduces no new judgement, only symmetry: `גלידה אניטה` is TLV-10 in the other script, and
   * without `גלידה` here it fails the same way.
   *
   * `מאפייה` and `מאפיה` are both listed because the two yod spellings are both current and
   * `normalise()` does not unify them.
   *
   * **What this block measured, stated as measured.** On the 15-case live TLV benchmark it is worth
   * **nothing**, and it costs one place: TLV-07's correct HaKosem branch slips from rank 2 to rank 3
   * because `פיצה הקוסם האיטלקי` now counts two identity words instead of three, pays less
   * extra-token penalty, and climbs 0.029 past it. The case fails either way — its top-1 is the
   * wrong branch with or without this block — and 10/15 is the score with it and without it.
   *
   * It is kept anyway, on two grounds that the benchmark cannot speak to. First, the benchmark is
   * **script-matched to the index by construction** (`handoff-2026-08-27` §6): every Hebrew case in
   * it is a bare venue name, so not one of them contains a Hebrew category noun and none of them
   * *can* show the benefit. Second, the rank slip is the penalty becoming more correct, not less:
   * `פיצה` really is not part of that shop's identity, and a scorer that says so is right even when
   * the row it lifts is one we did not want lifted. What TLV-07 actually needs is branch
   * disambiguation, which no word list provides.
   *
   * That is a judgement on thin evidence and it is written here so it can be reversed on better
   * evidence. Deleting this block is a one-line change and `score.test.ts` says what it protects.
   *
   * **Known and not fixed here:** Hebrew attaches the definite article, so `הבר` and `הפיצה` are
   * single tokens that this set cannot see. Teaching the tokeniser about `ה־` changes
   * `normalise()`'s output, which bumps `NORM_VERSION` and forces a full reload of `poi_index` —
   * a data migration, not a scoring change, and out of this task's scope.
   */
  readonly generic: ReadonlySet<string>;
  /**
   * Per `CategoryHint`, the tokens a candidate's provider category may contain to count as a
   * category match. Indexed **only** by a `CategoryHint` — never by a raw string. `11` §2 ruling 9:
   * the prototype's `CAT_TOKENS[hint]` is a `KeyError` for four of the seven values `09` §4.2's
   * schema can emit, and `categoryHintFor()` (`category-hint.ts`) is the total conversion that
   * makes this table safe to index.
   */
  readonly categoryTokens: Readonly<Record<CategoryHint, ReadonlySet<string>>>;
}

export const SCORING: ScoringConstants = Object.freeze({
  name: Object.freeze({ whole: 0.45, tokenCoverage: 0.55 }),
  total: Object.freeze({ name: 1, category: 0, datasetConfidence: 0 }),
  extraTokenPenalty: Object.freeze({ perToken: 0.04, max: 0.15 }),
  substringCredit: 0.97,
  minDistinctiveTokenLength: 2,
  bands: Object.freeze({ preselectScore: 0.92, preselectMargin: 0.05, confirmScore: 0.8 }),
  branchGuard: Object.freeze({ rivalScoreBand: 0.12 }),
  samePlaceMetres: 75,
  decisive: Object.freeze({ rivalNameSeparation: 0.02 }),
  defaultMaxResults: 5,
  address: Object.freeze({
    weight: 0.2,
    streetMatch: 0.9,
    streetOnly: 0.5,
    minStreetTokenLength: 3,
  }),
  addressNoise: Object.freeze(
    new Set([
      // Street-type nouns, Hebrew and English.
      'רחוב', 'רח', 'שדרות', 'שד', 'דרך', 'סמטה', 'סמטת', 'כביש', 'מתחם',
      'st', 'street', 'rd', 'road', 'ave', 'avenue', 'blvd', 'boulevard', 'square',
      // City and country words a caption appends and `address_line` usually does not.
      'תל', 'אביב', 'יפו', 'ישראל', 'israel', 'telaviv', 'tel', 'aviv', 'jaffa',
    ]),
  ),
  generic: Object.freeze(
    new Set([
      // The prototype's list, unchanged.
      'cafe', 'café', 'coffee', 'bar', 'restaurant', 'kitchen', 'the', 'and', 'a', 'of', 'de', 'co',
      'company', 'roasters', 'roastery', 'house', 'shop', 'tokyo', 'london', 'tel', 'aviv', 'hidden',
      'gem', 'best', 'ever', 'this', 'that', 'little', 'near', 'in', 'at',
      // Food-category nouns (TLV-RANK-1). What is sold, not who sells it.
      'gelato', 'gelateria', 'pizza', 'pizzeria', 'sushi', 'bakery', 'bakeries', 'brunch',
      'dessert', 'desserts',
      // Hebrew counterparts of entries above (TLV-RANK-1).
      'קפה', 'בר', 'מסעדה', 'בית', 'תל', 'אביב',
      'גלידה', 'גלידריה', 'פיצה', 'סושי', 'מאפייה', 'מאפיה',
    ]),
  ),
  categoryTokens: Object.freeze({
    cafe: Object.freeze(
      new Set(['cafe', 'coffee', 'coffee_shop', 'cafeteria', 'bakery', 'tea', 'dessert',
        'ice_cream', 'juice']),
    ),
    bar: Object.freeze(
      new Set(['bar', 'pub', 'cocktail', 'wine', 'beer', 'brewery', 'nightlife', 'lounge',
        'speakeasy']),
    ),
    restaurant: Object.freeze(
      new Set(['restaurant', 'food', 'dining', 'diner', 'ramen', 'sushi', 'noodle', 'pizza',
        'bistro', 'steak', 'izakaya', 'fast_food', 'buffet', 'deli', 'eatery']),
    ),
  }),
});
