-- 0019_saved_place_enrichment.sql — free-form tags, a one-sentence "why go", and named dishes,
-- stored PER SAVE (per user), derived server-side, and unwritable from a browser.
--
-- Deferred on 2026-08-23, now the workstream (execution-plan change log): "places to carry multiple
-- free-form tags/labels (e.g. 'Italian', 'matcha') rather than one fixed category, generated by the
-- AI from source content". Measured on the local database before writing this: `places.category`
-- holds 4 distinct values across 20 rows, 14 of them `restaurant` — no discriminating power at all,
-- so it cannot be the thing a library is organised by.
--
-- =============================================================================================
-- WHY `saved_places` AND NOT `places`. This is the load-bearing decision in this file.
-- =============================================================================================
--
-- `places` is shared across users (charter invariant 4: one physical place, many people, many
-- TikToks) and every column on it is a PROVIDER fact — `resolve_place` is its only writer, it runs
-- as `service_role`, and what it writes is geocoder output. A tag derived from a TikTok caption is
-- not a provider fact about the venue. It is a claim made by one creator in one video that one user
-- chose to import. Four consequences, in the order they matter:
--
--   1. PRIVACY. `places` is readable by any user who saved the same venue
--      (`places_select_if_saved`, 0006). Tags on `places` would therefore ship user A's
--      caption-derived free text into user B's browser. That text is unbounded model output over an
--      unbounded creator caption: it can carry a slur, a person's name, a political statement or an
--      in-joke, attributed to nobody and removable by nobody. `saved_places` is scoped to
--      `user_id = auth.uid()` in all four directions, so on `saved_places` this exposure does not
--      exist at all rather than being merely bounded. It is also the REVERSIBLE choice: per-user
--      tags can later be rolled up into a shared, unattributed aggregate; a shared column that user
--      B has already read cannot be un-read.
--   2. WRITE ORDERING. `resolve_place`'s update path is `coalesce(p_x, x)` — last non-null writer
--      wins. On a shared tags column, a second import of the same venue from an unrelated TikTok
--      would silently replace the first user's tags. The alternative, union-merge, accumulates
--      forever with no owner and no removal path. Neither is defensible; both disappear when the
--      column is per-user.
--   3. RE-IMPORT. `save_place` upserts on `(user_id, place_id)`, so re-importing the same post is
--      already idempotent for this row. These columns inherit that for free.
--   4. MERGES. `merge_places` moves `saved_places.place_id` onto the winner, so per-user values
--      travel with the user's own row and two merged venues never need their tag lists reconciled.
--
-- The usual objection — "the same venue saved by two users computes twice" — mostly dissolves on
-- inspection: the model call is cached on `extractions`, keyed `(source_id, model, prompt_version)`
-- (0004), so two users importing the SAME TikTok pay one call and both read the same cached
-- candidate. Two users importing DIFFERENT TikToks about the same venue SHOULD get different tags;
-- that is the recommendation differing, not waste.
--
-- `why_go` and `dishes` are the same answer for a stronger reason, and they are not arguable: they
-- are statements about one recommendation, not about the venue. They sit next to `extracted_reason`
-- (0015), which is exactly the same class of thing, and share its grant and writer story.
--
-- RUNNER-UP, named so nobody has to rediscover it: `saved_place_sources` — keyed (saved place,
-- source) — is the *most* precise home for `why_go`/`dishes`, and 0017's header already flags that
-- table as "the natural home for richer creator-commentary fields". It is rejected here for the same
-- reason 0016 denormalised `source_url` onto `saved_places`: the library read renders these on every
-- card, ~99% of saved places have exactly one source, and a join on the hot read is a real cost paid
-- for a distinction the product does not yet make. If per-source commentary is ever needed ("this
-- TikTok said X, that one said Y"), it goes there — not into a wider column here.
--
-- USER-AUTHORED TAGS ARE A DIFFERENT COLUMN, DELIBERATELY NOT ADDED HERE. `tags` below is
-- system-derived and holds NO client write grant, which is the whole point (see section 4). The day
-- the product lets a user add or remove their own tag, it gets `user_tags` beside `note` in the
-- overlay grant — reusing `tags` for it would re-open exactly the hole `current-state.md` §3.4
-- records, and would destroy the extracted-vs-authored provenance distinction as well.
--
-- WHAT THE CALLER MUST SEND, AND WHY IT IS NOT THE DISPLAY LABEL. This normaliser agrees with
-- `src/domain/places/normalise.ts` on CASE and disagrees with it on accents and punctuation, because
-- `unaccent()` is not IMMUTABLE and cannot be used here. Measured on this container against that
-- function:
--
--     'Pan-Asian'  ->  normalise(): 'pan asian'   normalize_tag(): 'pan-asian'
--     'Cafe'       ->  normalise(): 'cafe'        normalize_tag(): 'cafe'
--     'Cafe'(acute)->  normalise(): 'cafe'        normalize_tag(): unchanged, accent kept
--
-- So if the extraction layer stores its TITLE-CASED DISPLAY LABEL here, two videos emitting
-- 'Pan-Asian' and 'pan asian' produce ONE tag to the application (which de-duplicates on
-- `normalise()`) and TWO tags in this column — and the filter-chip query reads this column.
--
-- The rule, therefore: **the caller stores `normalise()`'s output and the UI title-cases at render**
-- (`titleCase` already exists in `src/domain/extraction/tags.ts`). `normalise()`'s output is a fixed
-- point of `normalize_tag()` — verified on this container for every case above — so the database
-- rewrites nothing, makes no competing identity claim, and `current-state.md` §4's "normalise() is
-- the only answer to are these the same text?" still holds with one answer rather than two. What the
-- functions below are for is HYGIENE and BOUNDS, which is a different job from identity.
--
-- OUT OF SCOPE, deliberately, by owner decision on 2026-08-27: cross-script place ALIASES (the
-- Hebrew-caption/English-caption duplicate-`places`-row defect). That reaches `resolve_place`, the
-- near-duplicate guard and the identity rules, which is a different concern from making what we
-- extract useful. It is a live defect with a deferred fix; the design is written up in the
-- place-aliases document the orchestrator is landing alongside this migration.

begin;

-- ---------------------------------------------------------------------------------------------
-- 1. THE NORMALISATION RULE, DEFINED ONCE, ENFORCED BY THE DATABASE
-- ---------------------------------------------------------------------------------------------
-- The caller is not trusted to normalise. A BEFORE trigger rewrites these columns through the
-- functions below on every write, and CHECK constraints then assert the stored value IS the
-- normalised form. The trigger makes it always true; the CHECK makes it provable, and would catch a
-- future write path that arrived with the trigger disabled.
--
-- HOW THE INVISIBLE CHARACTERS ARE FOUND, and why there is not a hand-written list of Unicode
-- ranges here. Measured on this container (en_US.UTF-8): `[^[:graph:][:space:]]` matches exactly
-- U+0001-class controls, SOFT HYPHEN, ZWSP, LRM, RLO, WORD JOINER and BOM, while matching none of
-- `a`, Hebrew alef or katakana; and `[[:space:]]` matches TAB, NBSP and IDEOGRAPHIC SPACE. So two
-- POSIX classes do what a range list would do, without a range list to get wrong. This depends on
-- the database ctype, which is fixed at initdb and identical on the hosted projects.
--
-- Stripping bidi and zero-width characters is not tidiness. These strings are rendered as chips in
-- the UI; `current-state.md` §3.13 already records a case where a bidi control reaching a log line
-- visually reversed a terminal viewer, and inside a tag it would do the same to the surrounding
-- page.
--
-- WHAT IS DELIBERATELY *NOT* FOLDED. `normalize(t, NFKC)` is IMMUTABLE in PG13+ (measured:
-- pg_proc.provolatile = 'i'), so it is legal in a CHECK and an index, and it folds fullwidth /
-- compatibility forms — a real win for Japanese input at no cost. Accents are NOT stripped:
-- `unaccent()` is not IMMUTABLE (0001's header says so, which is why `place_name_key` does not fold
-- them either), and the ASCII-only workaround — rejecting non-Latin — would reject Hebrew tags in a
-- product whose first city is Tel Aviv. So `café` and `cafe` remain two distinct tags. Reducing that
-- is the extraction layer's job (a controlled vocabulary), not the database's; inventing a
-- database-side folding rule here would be a second, quietly different normalisation, which is the
-- exact failure `current-state.md` §4 warns about.

create or replace function public.normalize_tag(p text) returns text
language sql immutable parallel safe
as $fn$
  -- The final predicate is not tidiness: a label with no letter and no digit ('...', '&', '--')
  -- carries no information and would render as an unclickable chip. Dropping it is
  -- canonicalisation, the same class of thing as dropping an empty string — NOT the same as the
  -- bounds check below, which REFUSES the write rather than discarding a real label. Punctuation
  -- inside an otherwise real label is kept, because '24/7', 'b.y.o.b' and 'bring-a-friend' are all
  -- legitimate tags; this is deliberately weaker than place_name_key(), which strips every
  -- non-alphanumeric character.
  select case when v ~ '[[:alnum:]]' then v end
    from (
      select nullif(btrim(
        regexp_replace(
          regexp_replace(lower(normalize(coalesce(p, ''), NFKC)),
                         '[^[:graph:][:space:]]', '', 'g'), -- controls, zero-width, bidi, BOM
          '[[:space:]]+', ' ', 'g')                          -- TAB / NBSP / U+3000 -> one space
      ), '') v
    ) d;
$fn$;

comment on function public.normalize_tag(text) is
  'The canonical form of one short free-form label: NFKC, lowercased, invisible/bidi/control '
  'characters removed, all whitespace collapsed to single ASCII spaces, trimmed; empty, or with no '
  'alphanumeric character at all, => NULL. '
  'IMMUTABLE so it is usable in CHECK constraints and indexes. Does NOT fold accents or scripts — '
  'see 0019''s header for why, and src/domain/places/normalise.ts for the application-side rule.';

-- The list form: normalise every element, drop what normalises to nothing, de-duplicate while
-- KEEPING FIRST-SEEN ORDER (the extractor's ordering is meaningful — the first tag is the most
-- salient and the UI renders it first), and collapse an empty result to NULL.
--
-- ONE EMPTY STATE, NOT TWO. `'{}'` is never storable: it normalises to NULL, and the bounds CHECK
-- would reject it anyway. Two representations of "no tags" is precisely the class of bug
-- `current-state.md` §4 keeps catching. The UI reads this as `tags ?? []`.
create or replace function public.normalize_tag_list(p text[]) returns text[]
language sql immutable parallel safe
as $fn$
  select nullif(
    coalesce((
      select array_agg(d.t order by d.ord)
        from (select public.normalize_tag(u.v) t, min(u.o) ord
                from unnest(p) with ordinality as u(v, o)
               where public.normalize_tag(u.v) is not null
               group by 1) d
    ), '{}'::text[]),
    '{}'::text[]);
$fn$;

comment on function public.normalize_tag_list(text[]) is
  'normalize_tag() over an array: elements normalised, empties dropped, duplicates removed keeping '
  'first-seen order, empty result => NULL. NULL is the ONLY representation of "no labels"; ''{}'' is '
  'not storable. IMMUTABLE.';

-- The bounds a normalised list must satisfy. A separate function because a CHECK constraint may not
-- contain a subquery, and "every element is at most N characters" needs one — so it is hidden inside
-- an IMMUTABLE function, which a CHECK may call.
--
-- DELIBERATELY REJECTS RATHER THAN TRUNCATES. If the extractor emits eleven tags, this fails the
-- write loudly instead of silently discarding three. Quietly dropping model output is exactly the
-- "convert uncertainty into certainty" move the working agreement forbids; the bound belongs in the
-- extraction schema, and this is the backstop that proves it is actually there.
create or replace function public.tag_list_within(p text[], p_max_count int, p_max_len int)
returns boolean
language sql immutable parallel safe
as $fn$
  select p is null or (
       array_position(p, null) is null
   and cardinality(p) between 1 and p_max_count
   and (select coalesce(bool_and(length(t) between 1 and p_max_len), true) from unnest(p) t)
  );
$fn$;

comment on function public.tag_list_within(text[], integer, integer) is
  'Bounds predicate for a label array: no NULL elements, 1..p_max_count entries, every entry '
  '1..p_max_len characters. A NULL array passes — absent is a legal state. IMMUTABLE, so it is '
  'callable from a CHECK constraint, which is the only reason it is a function: a CHECK may not '
  'contain the subquery the per-element length test needs.';

-- A sentence, not a label: identical hygiene, but NOT lowercased — capitalisation is meaningful in
-- model-written prose.
create or replace function public.normalize_sentence(p text) returns text
language sql immutable parallel safe
as $fn$
  select case when v ~ '[[:alnum:]]' then v end
    from (
      select nullif(btrim(
        regexp_replace(
          regexp_replace(normalize(coalesce(p, ''), NFKC),
                         '[^[:graph:][:space:]]', '', 'g'),
          '[[:space:]]+', ' ', 'g')
      ), '') v
    ) d;
$fn$;

comment on function public.normalize_sentence(text) is
  'normalize_tag() without the lowercasing, for model-written prose: NFKC, invisible/bidi/control '
  'characters removed, whitespace collapsed, trimmed; empty, or with no alphanumeric character at '
  'all, => NULL. IMMUTABLE.';

-- EXECUTE. These four are pure, IMMUTABLE, SECURITY INVOKER, and touch no table — the same class as
-- `km_between` (0007), which `authenticated` already holds.
--
-- `authenticated` MUST hold EXECUTE, and this is measured rather than assumed. A CHECK constraint's
-- function call IS permission-checked against the writing role (verified on this container: the
-- insert fails 42501 `permission denied for function`), and Postgres re-evaluates EVERY check
-- constraint of a row on UPDATE. Without the grant, a user editing the `note` on a row that happens
-- to carry tags would have their edit refused — a latent break of a shipped feature (`L1-F7-T3`).
-- A trigger function, by contrast, is NOT permission-checked when the trigger fires (also measured),
-- so `normalize_saved_place_enrichment` below is granted to nobody.
--
-- `revoke ... from public` is the load-bearing line, not a formality: EXECUTE defaults to PUBLIC on
-- every newly created function, and `revoke ... from anon` does not remove a privilege held through
-- PUBLIC. That is 0009's bug and then 0018's bug, in this repo, twice.
-- `supabase/tests/inventory.sql` check 6 is the exhaustive assertion and is updated alongside this.
revoke all on function public.normalize_tag(text)                       from public, anon, authenticated;
revoke all on function public.normalize_tag_list(text[])                from public, anon, authenticated;
revoke all on function public.tag_list_within(text[], integer, integer) from public, anon, authenticated;
revoke all on function public.normalize_sentence(text)                  from public, anon, authenticated;

grant execute on function public.normalize_tag(text)                       to authenticated, service_role;
grant execute on function public.normalize_tag_list(text[])                to authenticated, service_role;
grant execute on function public.tag_list_within(text[], integer, integer) to authenticated, service_role;
grant execute on function public.normalize_sentence(text)                  to authenticated, service_role;

-- ---------------------------------------------------------------------------------------------
-- 2. THE COLUMNS
-- ---------------------------------------------------------------------------------------------
-- SHAPE: `text[]`, not a join table and not `jsonb`. Judged at THIS product's scale, which is
-- hundreds of saved places per user, not millions.
--
--   A join table (`saved_place_tags`) would need its own RLS + FORCE + REVOKE + four policies, its
--   own composite FK to stop `user_id` drifting (the shape `saved_place_sources` uses), its own
--   column-level grants, a second write in every save path, and a join on the hot library read. All
--   of that buys per-tag rows and set operations that nothing in this product needs. At <= 8 tags on
--   a few hundred rows per user it is unjustified, and saying so is part of the ruling rather than
--   an omission from it.
--
--   `jsonb` is worse than `text[]` here specifically: no cheap `distinct unnest` for the filter-chip
--   query, `@>` carries document-containment semantics rather than scalar membership, and it invites
--   nested structure that will drift away from "a bounded list of short labels".
--
-- NULLABLE, AND NULL IS THE ONLY EMPTY. The 20 rows already in this database were extracted under v1
-- and have no tags; they stay NULL and NOTHING IS BACKFILLED — re-extraction spends model calls
-- against a hard 500/day ceiling and is the owner's data decision, not a migration's. So an absent
-- tag list is the normal, renderable state, not a broken one, and it stays the majority state for
-- some time. Same posture as `extracted_reason` (0015) and `source_url` (0016).

alter table public.saved_places
  add column tags   text[],
  add column why_go text,
  add column dishes text[];

alter table public.saved_places
  add constraint saved_places_tags_normalised
    check (tags is null or tags = public.normalize_tag_list(tags)),
  add constraint saved_places_tags_bounded
    check (public.tag_list_within(tags, 8, 32)),
  add constraint saved_places_dishes_normalised
    check (dishes is null or dishes = public.normalize_tag_list(dishes)),
  add constraint saved_places_dishes_bounded
    check (public.tag_list_within(dishes, 8, 64)),
  add constraint saved_places_why_go_normalised
    check (why_go is null or why_go = public.normalize_sentence(why_go)),
  add constraint saved_places_why_go_bounded
    check (why_go is null or length(why_go) between 1 and 280);

comment on column public.saved_places.tags is
  'Short free-form labels for THIS save, derived by the extractor from the source post: cuisine, '
  'vibe, occasion ("italian", "matcha", "late night"). Per-user by design — see 0019''s header for '
  'why these are not on `places`. At most 8, each 1..32 characters, normalised by '
  'normalize_tag_list() and re-asserted by CHECK. NULL means "no labels" and is the only empty '
  'representation. System-derived: no client INSERT or UPDATE grant exists and none is ever added; '
  'the sole writer is apply_saved_place_extraction() under service_role. A future user-authored tag '
  'list is a SEPARATE column (`user_tags`), never this one.';
comment on column public.saved_places.why_go is
  'One model-written sentence saying why this post recommended this place. Distinct from '
  '`extracted_reason`, which is a VERBATIM caption substring (0017) — this is prose, and the two '
  'answer different questions: "what did the caption literally say" versus "why, in one line". NULL '
  'when the caption says nothing worth paraphrasing, which is a normal outcome, not a failure. '
  '<= 280 characters. System-derived; no client write grant.';
comment on column public.saved_places.dishes is
  'Named dishes or items the post called out, normalised the same way as `tags` (lowercased — the UI '
  'decides display casing; one normalisation rule beats two). At most 8, each 1..64 characters. NULL '
  'when the post names none. System-derived; no client write grant.';

-- ---------------------------------------------------------------------------------------------
-- 3. THE TRIGGER THAT MAKES NORMALISATION UNCONDITIONAL
-- ---------------------------------------------------------------------------------------------
-- Fires before the CHECK constraints, so on the normal path those CHECKs can never fire. What they
-- still catch is a value out of BOUNDS after normalisation (nine tags, a 60-character tag) — which
-- is the honest failure this deliberately does not paper over.
create or replace function public.normalize_saved_place_enrichment() returns trigger
language plpgsql
set search_path = public, pg_temp
as $fn$
begin
  new.tags   := public.normalize_tag_list(new.tags);
  new.dishes := public.normalize_tag_list(new.dishes);
  new.why_go := public.normalize_sentence(new.why_go);
  return new;
end;
$fn$;

-- The trigger name sorts BEFORE `saved_places_touch`: Postgres fires BEFORE-row triggers in name
-- order, and while these two touch disjoint columns today, relying on that silently is how the next
-- trigger added to this table becomes an ordering bug.
create trigger saved_places_normalize_enrichment
  before insert or update on public.saved_places
  for each row execute function public.normalize_saved_place_enrichment();

revoke all on function public.normalize_saved_place_enrichment() from public, anon, authenticated;
-- Granted to nobody: a trigger function is not permission-checked when the trigger fires (measured
-- on this container), so an EXECUTE grant here would be reachable surface with no purpose.

-- ---------------------------------------------------------------------------------------------
-- 4. THE ONLY WRITER — AND WHY THE `extracted_reason` SCAR IS NOT REPEATED
-- ---------------------------------------------------------------------------------------------
-- THE SCAR, stated so the fix is checkable against it. `current-state.md` §3.4: 0015 deliberately
-- kept `extracted_reason` out of the INSERT grant so it would stay system-derived; 0017 had to grant
-- it back, because `save_place` is SECURITY INVOKER and an invoker-mode INSERT is bound by the
-- CALLER's column grants. The residue is that an authenticated client can POST straight to
-- `/saved_places` with any `extracted_reason` it likes and it lands verbatim. RLS bounds that to the
-- caller's own row, so it is a user lying to themselves — but it contradicts the standing rule that
-- the browser may never send a place fact.
--
-- THE ROOT CAUSE IS THE GRANT, NOT THE FUNCTION. Whatever writes these columns must run as a role
-- the browser does not have. So: the writer here runs as `service_role`, the three new columns get
-- NO client grant of any kind, and a forged value POSTed to `/saved_places` is refused 42501 by the
-- database. That is enforcement, not intent, and it is checkable in one query against
-- `information_schema.column_privileges`.
--
-- WHY SECURITY INVOKER AND NOT DEFINER. `current-state.md` §3.4 proposes making `save_place`
-- SECURITY DEFINER as the fix for `extracted_reason`. Flagging that as contradicting
-- `docs/agent-guardrails.md` §5.18 was correct at the time and the contradiction is now resolved:
-- §5.18 had over-compressed `security.md` §1 invariant 1 into a blanket ban, and was corrected on
-- 2026-08-27 to carry its three qualifiers again (reads global rows / writes a column the caller
-- holds no grant on / targets a row from a caller-supplied id rather than `auth.uid()`). So §3.4's
-- proposal is not forbidden — though a `service_role` writer is the cheaper fix and is now the
-- recommended shape. This function needs neither: `service_role` already holds
-- table-level ALL on `saved_places` (0012, asserted by `inventory.sql` check 9), so SECURITY INVOKER
-- is sufficient and strictly safer. No elevation is created anywhere in this migration.
--
-- WHY IT TAKES VALUES RATHER THAN READING `extractions.candidates` ITSELF. The shape of that jsonb
-- is owned by `docs/09-extraction-and-resolution.md` and is being revised right now; 0004's own
-- comment says the schema does not model it. Reaching into `candidates->>'whyGo'` from a migration
-- would hard-code a field name that is explicitly still moving, and would break silently when it
-- shifts. The security property does not depend on where the value is computed — it depends on WHO
-- may write the column, and that is settled by the grant. The server derives these from the stored
-- extraction exactly as it already derives `extractedReason` today.
--
-- FIRST WRITER WINS (`coalesce` per column), matching `extracted_reason` (0017) and `source_url`
-- (0016): a later, unrelated import of the same venue does not silently rewrite what the first one
-- recorded. Union-across-sources would need per-source attribution, and that lives on
-- `saved_place_sources`, not in a wider column here.
create or replace function public.apply_saved_place_extraction(
  p_saved_place_id uuid,
  p_user_id        uuid,
  p_tags           text[] default null,
  p_why_go         text   default null,
  p_dishes         text[] default null
) returns void
language plpgsql security invoker set search_path = public, pg_temp
as $fn$
begin
  if p_user_id is null then
    raise exception 'apply_saved_place_extraction requires a user id' using errcode = '22004';
  end if;

  -- The ownership predicate is in the WHERE clause on purpose. `service_role` has BYPASSRLS, so no
  -- policy protects this row: the function must refuse to write another user's save itself. Same
  -- discipline as `start_import` (0007) and `apply_saved_place_source_link` (0016). A mismatched
  -- user id updates zero rows and returns quietly — the caller already knows which save it created.
  update saved_places sp
     set tags   = coalesce(sp.tags,   public.normalize_tag_list(p_tags)),
         why_go = coalesce(sp.why_go, public.normalize_sentence(p_why_go)),
         dishes = coalesce(sp.dishes, public.normalize_tag_list(p_dishes))
   where sp.id = p_saved_place_id
     and sp.user_id = p_user_id;
end;
$fn$;

comment on function public.apply_saved_place_extraction(uuid, uuid, text[], text, text[]) is
  'The ONLY writer of saved_places.tags / why_go / dishes. service_role only: those three columns '
  'carry no grant for anon or authenticated, so a browser cannot set them through PostgREST at all — '
  'which is how the extracted_reason hole (current-state.md §3.4) is avoided rather than repeated. '
  'SECURITY INVOKER, so it creates no elevation; it enforces ownership in its own WHERE clause '
  'because service_role bypasses RLS. First writer wins, per column.';

revoke all on function public.apply_saved_place_extraction(uuid, uuid, text[], text, text[])
  from public, anon, authenticated;
grant execute on function public.apply_saved_place_extraction(uuid, uuid, text[], text, text[])
  to service_role;

-- NO GRANT IS ADDED FOR THE THREE NEW COLUMNS, on any statement, for any browser role. 0015's closed
-- INSERT column list and 0006's closed UPDATE column list on `saved_places` are left exactly as they
-- are, and that is what makes the omission effective: because both grants are column-scoped rather
-- than table-level, a new column arrives ungranted by default. (0017's header makes the same point
-- about `saved_place_sources`, which is why it narrowed that table's table-level grants.)

-- ---------------------------------------------------------------------------------------------
-- 5. THE INDEX, AND AN HONEST NOTE ABOUT IT
-- ---------------------------------------------------------------------------------------------
-- The three queries the UI runs:
--   Q1  every place in my library carrying tag X   -> user_id = $1 and tags @> array[$2]
--   Q2  the distinct set of tags across my library -> select distinct unnest(tags) ... user_id = $1
--   Q3  Q1 narrowed by city                        -> Q1 joined to places on locality
--
-- Only Q1/Q3 can use a GIN index at all; Q2 must read the user's own rows whatever happens. At a few
-- hundred rows per user the planner prefers `saved_places_user_recent_idx` plus a heap filter, so
-- this index is currently DECORATIVE — measured with EXPLAIN on this database, not assumed. It is
-- created anyway because it is nearly free on a mostly-NULL array column, it is the shape a reviewer
-- expects, and dropping an unused index later is trivial where discovering a missing one under load
-- is not. If it is still unused when a library grows, drop it.
--
-- Deliberately NOT done: installing `btree_gin` to build the composite `gin (user_id, tags)` that
-- would genuinely serve Q1. It needs a new extension, and `inventory.sql` check 8 allow-lists
-- extensions for a reason (D6). Not worth it for hundreds of rows.
create index saved_places_tags_gin on public.saved_places using gin (tags);

commit;
